// Generated by CoffeeScript 1.10.0
var request;

request = new XMLHttpRequest;

(function() {
  var $output, $searchInput, initSearch, jargon;
  $searchInput = document.getElementById('search');
  $output = document.getElementById('results');
  jargon = {};
  initSearch = function(data) {
    var entries, h;
    entries = data.map(function(entry) {
      jargon[entry.name] = entry.html;
      return entry.name;
    });
    h = horsey($searchInput, {
      suggestions: entries,
      limit: 8,
      render: function(li, suggestion) {
        return li.innerHTML = suggestion;
      },
      set: function(value) {
        $searchInput.value = value;
        return $output.innerHTML = jargon[value];
      }
    });
    return $searchInput.addEventListener('horsey-filter', function(e) {});
  };
  request.open('GET', 'js/entries.json', true);
  request.onload = function() {
    var data;
    if (request.status >= 200 && request.status < 400) {
      data = JSON.parse(request.responseText);
      return initSearch(data);
    }
  };
  request.onerror = function() {};
  return request.send();
})();
